### ISSUE TITLE
Unbundling hawktracer

### ISSUE THREAD

**Issue by eclipseo** [AlexEne/rust_hawktracer_sys#5]
Could you provide a way to use system-wide hawktracer, through pkgconfig ideally?

Thank you.

Here's an example from zstd: https://github.com/gyscos/zstd-rs/blob/master/zstd-safe/zstd-sys/build.rs

**Comment by AlexEne** [comment]
Yes, it should be failry easy. I'll include this in the next release

**Comment by AlexEne** [comment]
`pkg_config` is a new option available in hawktracer 0.7
